# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 633)
        MainWindow.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/* Modern Application Style */\n"
"QMainWindow, QDialog {\n"
"    background-color: #121212;\n"
"    color: #f5f5f5;\n"
"    font-family: \"Inter\", \"Roboto\", \"Segoe UI\", sans-serif;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"/* PyQtGraph Styling */\n"
"QWidget[class=\"PlotWidget\"] {\n"
"    background-color: #1e1e1e;\n"
"    border: 1px solid #333333;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* For plot background within the PyQtGraph widget */\n"
"/* Note: Apply these in Python code:\n"
"   plot.setBackground(\'#1e1e1e\')\n"
"   plot.showGrid(x=True, y=True, alpha=0.2)\n"
"   plot.getAxis(\'bottom\').setPen(color=\'#808080\')\n"
"   plot.getAxis(\'left\').setPen(color=\'#808080\')\n"
"*/\n"
"\n"
"/* Push Buttons */\n"
"QPushButton {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 8px 16px;\n"
"    border-radius: 8px;\n"
"    font-weight: 600;\n"
"    min-width: 90px;\n"
"    text-transform: uppercase;\n"
"    font-size: 9pt;\n"
"    letter-spacing: 0.5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b82f6;\n"
"    transition: background-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #333333;\n"
"    color: #666666;\n"
"}\n"
"\n"
"/* Combo Boxes */\n"
"QComboBox {\n"
"    border: 2px solid #333333;\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"    selection-background-color: white;\n"
"    selection-color: white;\n"
"    min-width: 120px;\n"
"    font-family: \"Inter\", \"Roboto\", \"Segoe UI\", sans-serif;\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #2563eb;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    border: 2px solid #2563eb;\n"
"    background-color:  #1e1e1e;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right;\n"
"    width: 24px;\n"
"    border-left: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #333333;\n"
"    selection-background-color: #2563eb;\n"
"    selection-color: white;\n"
"    background-color: #1e1e1e;\n"
"    outline: 0px;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* Spin Box */\n"
"QSpinBox, QDoubleSpinBox {\n"
"    border: 2px solid #333333;\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    background-color: #1e1e1e;\n"
"    color: #f5f5f5;\n"
"    selection-background-color: #2563eb;\n"
"    selection-color: white;\n"
"    min-width: 90px;\n"
" font-family: \"Inter\", \"Roboto\", \"Segoe UI\", sans-serif;\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QSpinBox:hover, QDoubleSpinBox:hover {\n"
"    border: 2px solid #2563eb;\n"
"}\n"
"\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border-left: none;\n"
"    border-top-right-radius: 6px;\n"
"    background-color: #333333;\n"
"    margin-right: 2px;\n"
"    margin-top: 2px;\n"
"}\n"
"\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    width: 22px;\n"
"    border-left: none;\n"
"    border-bottom-right-radius: 6px;\n"
"    background-color: #333333;\n"
"    margin-right: 2px;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover,\n"
"QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover {\n"
"    background-color: #2563eb;\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {\n"
"    image: url(up-arrow.png);  /* Replace with path to your arrow icon */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {\n"
"    image: url(down-arrow.png);  /* Replace with path to your arrow icon */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"/* Additional Modern Styling */\n"
"QLabel {\n"
"    color: #f5f5f5;\n"
"     font-family: \"Inter\", \"Roboto\", \"Segoe UI\", sans-serif;\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid #333333;\n"
"    border-radius: 8px;\n"
"    margin-top: 24px;\n"
"    font-weight: 600;\n"
"    padding-top: 16px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 10px;\n"
"    color: #3b82f6;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background-color: #1e1e1e;\n"
"    height: 8px;\n"
"    margin: 0px 0px 0px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #1e1e1e;\n"
"    width: 8px;\n"
"    margin: 0px 0px 0px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal, QScrollBar::handle:vertical {\n"
"    background-color: #555555;\n"
"    border-radius: 4px;\n"
"    min-width: 30px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover, QScrollBar::handle:vertical:hover {\n"
"    background-color: #2563eb;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: none;\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* Tooltip */\n"
"QToolTip {\n"
"    border: 1px solid #333333;\n"
"    background-color: #1e1e1e;\n"
"    color: #f5f5f5;\n"
"    padding: 5px;\n"
"    border-radius: 4px;\n"
"    opacity: 220;\n"
"}\n"
"\n"
"/* Status Bar */\n"
"QStatusBar {\n"
"    background-color: #121212;\n"
"    color: #808080;\n"
"    border-top: 1px solid #333333;\n"
"}\n"
"\n"
"/* Tab Widget */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #333333;\n"
"    border-radius: 8px;\n"
"    top: -2px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #1e1e1e;\n"
"    color: #808080;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    margin-right: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"}\n"
"\n"
"QTabBar::tab:hover:!selected {\n"
"    background-color: #262626;\n"
"    color: #f5f5f5;\n"
"}\n"
"/* Modern Checkbox Styling for Dark UI */\n"
"QCheckBox {\n"
"    spacing: 8px;\n"
"    color: #f5f5f5;\n"
"    font-family: \"Inter\", \"Roboto\", \"Segoe UI\", sans-serif;\n"
"    font-size: 10pt;\n"
"    font-weight: 500;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 4px;\n"
"    border: 2px solid #555555;\n"
"    background-color: #1e1e1e;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid #3b82f6;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #1e1e1e;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    background-color: #262626;\n"
"    border: 2px solid #3b82f6;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #2563eb;\n"
"    border: 2px solid #2563eb;\n"
"    image: url(check.png); /* Replace with path to a white checkmark icon */\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #3b82f6;\n"
"    border: 2px solid #3b82f6;\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate {\n"
"    background-color: #4b5563;\n"
"    border: 2px solid #4b5563;\n"
"    image: url(dash.png); /* Replace with path to a white dash/minus icon */\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:hover {\n"
"    background-color: #6b7280;\n"
"    border: 2px solid #6b7280;\n"
"}\n"
"\n"
"QCheckBox:disabled {\n"
"    color: #6b7280;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    border: 2px solid #333333;\n"
"    background-color: #262626;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plot_hyprid = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_hyprid.sizePolicy().hasHeightForWidth())
        self.plot_hyprid.setSizePolicy(sizePolicy)
        self.plot_hyprid.setObjectName("plot_hyprid")
        self.gridLayout_6.addWidget(self.plot_hyprid, 2, 3, 1, 1)
        self.plot_output = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_output.sizePolicy().hasHeightForWidth())
        self.plot_output.setSizePolicy(sizePolicy)
        self.plot_output.setObjectName("plot_output")
        self.gridLayout_6.addWidget(self.plot_output, 2, 1, 1, 1)
        self.plot_second = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_second.sizePolicy().hasHeightForWidth())
        self.plot_second.setSizePolicy(sizePolicy)
        self.plot_second.setObjectName("plot_second")
        self.gridLayout_6.addWidget(self.plot_second, 0, 3, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setStyleSheet("    background-color: #2563eb;\n"
"")
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_6.addWidget(self.line_13, 1, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setStyleSheet("    background-color: #2563eb;\n"
"")
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_6.addWidget(self.line_14, 1, 3, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setStyleSheet("    background-color: #2563eb;\n"
"")
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_6.addWidget(self.line_16, 0, 2, 1, 1)
        self.plot_original = PlotWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_original.sizePolicy().hasHeightForWidth())
        self.plot_original.setSizePolicy(sizePolicy)
        self.plot_original.setObjectName("plot_original")
        self.gridLayout_6.addWidget(self.plot_original, 0, 1, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setStyleSheet("    background-color: #2563eb;\n"
"")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_6.addWidget(self.line_15, 2, 2, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_browse = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browse.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.verticalLayout_4.addWidget(self.pushButton_browse)
        self.comboBox_noise = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_noise.setObjectName("comboBox_noise")
        self.comboBox_noise.addItem("")
        self.comboBox_noise.addItem("")
        self.comboBox_noise.addItem("")
        self.comboBox_noise.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_noise)
        self.comboBox_lowpass = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_lowpass.setObjectName("comboBox_lowpass")
        self.comboBox_lowpass.addItem("")
        self.comboBox_lowpass.addItem("")
        self.comboBox_lowpass.addItem("")
        self.comboBox_lowpass.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_lowpass)
        self.comboBox_edge = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_edge.setObjectName("comboBox_edge")
        self.comboBox_edge.addItem("")
        self.comboBox_edge.addItem("")
        self.comboBox_edge.addItem("")
        self.comboBox_edge.addItem("")
        self.comboBox_edge.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_edge)
        self.comboBox_freq = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_freq.setObjectName("comboBox_freq")
        self.comboBox_freq.addItem("")
        self.comboBox_freq.addItem("")
        self.comboBox_freq.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_freq)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_cutoff = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cutoff.setObjectName("spinBox_cutoff")
        self.horizontalLayout_2.addWidget(self.spinBox_cutoff)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_global = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_global.setObjectName("checkBox_global")
        self.horizontalLayout.addWidget(self.checkBox_global)
        self.checkBox_local = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_local.setObjectName("checkBox_local")
        self.horizontalLayout.addWidget(self.checkBox_local)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_equalize = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_equalize.setObjectName("checkBox_equalize")
        self.horizontalLayout_6.addWidget(self.checkBox_equalize)
        self.checkBox_normalize = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_normalize.setObjectName("checkBox_normalize")
        self.horizontalLayout_6.addWidget(self.checkBox_normalize)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.pushButton_disthist = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_disthist.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_disthist.setObjectName("pushButton_disthist")
        self.verticalLayout_4.addWidget(self.pushButton_disthist)
        self.pushButton_grayscale = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_grayscale.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_grayscale.setObjectName("pushButton_grayscale")
        self.verticalLayout_4.addWidget(self.pushButton_grayscale)
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reset.sizePolicy().hasHeightForWidth())
        self.pushButton_reset.setSizePolicy(sizePolicy)
        self.pushButton_reset.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.verticalLayout_4.addWidget(self.pushButton_reset)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse"))
        self.comboBox_noise.setItemText(0, _translate("MainWindow", "No Noise"))
        self.comboBox_noise.setItemText(1, _translate("MainWindow", "Gaussian Noise"))
        self.comboBox_noise.setItemText(2, _translate("MainWindow", "Salt & Pepper Noise"))
        self.comboBox_noise.setItemText(3, _translate("MainWindow", "Uniform Noise"))
        self.comboBox_lowpass.setItemText(0, _translate("MainWindow", "LP Filter Type"))
        self.comboBox_lowpass.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.comboBox_lowpass.setItemText(2, _translate("MainWindow", "Average"))
        self.comboBox_lowpass.setItemText(3, _translate("MainWindow", "Median"))
        self.comboBox_edge.setItemText(0, _translate("MainWindow", "Edge Detector"))
        self.comboBox_edge.setItemText(1, _translate("MainWindow", "Sobel Mask"))
        self.comboBox_edge.setItemText(2, _translate("MainWindow", "Roberts Mask"))
        self.comboBox_edge.setItemText(3, _translate("MainWindow", "Canny Mask"))
        self.comboBox_edge.setItemText(4, _translate("MainWindow", "Prewitt Mask"))
        self.comboBox_freq.setItemText(0, _translate("MainWindow", "Freq Domain Filter"))
        self.comboBox_freq.setItemText(1, _translate("MainWindow", "Low Pass Filter"))
        self.comboBox_freq.setItemText(2, _translate("MainWindow", "High Pass Filter"))
        self.label.setText(_translate("MainWindow", "   Cutoff Freq"))
        self.checkBox_global.setText(_translate("MainWindow", "Global Threshold"))
        self.checkBox_local.setText(_translate("MainWindow", "Local Threshold"))
        self.checkBox_equalize.setText(_translate("MainWindow", "Equalize             "))
        self.checkBox_normalize.setText(_translate("MainWindow", "Normalize"))
        self.pushButton_disthist.setText(_translate("MainWindow", "Distribution and Histogram"))
        self.pushButton_grayscale.setText(_translate("MainWindow", "gray scale"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
